export const LOGIN_START = 'AUTH_LOGIN_START';
export const LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const SET_HOMEWORKS = 'SET_HOMEWORKS';


export const SET_HISTORY = 'SET_HISTORY';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
